"use client"

import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Transition from "@/components/Transition";
import { arrowdown, hero } from "../../public/images/exports";
import { useRef } from "react";



const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const firstText = useRef(null)
  const secondText = useRef(null)


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Transition>
        <div className={styles.body}>
          <div className="body-main">
            <Image src={hero} width={100} height={100} className="hero-image" alt="hero-image" />
            <div className="body-container">
              <div className="body-text">
                <div style={{marginBottom: "3rem"}}><Image src={arrowdown} width={40} height={40} alt="arrow" /></div>
                <div className="body-text-p">
                  <p>Full Stack <br /> Web Developer</p>
                </div>
              </div>

              {/* <div className="slider-container">
                <div className="slider">
                  <p ref={firstText}>isaac tesha - </p>
                  <p ref={secondText}>isaac tesha - </p>
                </div>
              </div> */}
            </div>
          </div>
        </div>
      </Transition>
    </>
  );
}
